FROM node:lts-slim

# Mount the source folder
VOLUME /usr/src/

# Mount the uploads folder
VOLUME /usr/uploads

# Set the working directory
WORKDIR /usr/

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE ${API_PORT}

# Command to run the application
CMD ["node", "src/app.js"]